apiVersion: v1
data:
  README: ${README}
  cwallet.sso: ${cwallet_sso}
  ewallet.p12: ${ewallet_p12}
  keystore.jks: ${keystore_jks}
  ojdbc.properties: ${ojdbc_properties}
  sqlnet.ora: ${sqlnet_ora}
  tnsnames.ora: ${tnsnames_ora}
  truststore.jks: ${truststore_jks}
  user_name: QURNSU4=
kind: Secret
metadata:
  name: atp-demo-binding-order
