apiVersion: v1
kind: Service
metadata:
  name: orderandinventoryadmin
  labels:
    app: orderandinventoryadmin
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector:
    app: orderandinventoryadmin
