apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
  annotations: # prometheus integration
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector:
    app: inventory
