apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: supplier-helidon-se
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: supplier
        version: helidon-se
    spec:
      containers:
      - name: supplier
        image: docker.io/paulparkinson/supplier-helidon-se:0.1
        imagePullPolicy: Always
        env:
        - name: database.url
          valueFrom:
            secretKeyRef:
              name: oracledb-service-broker-secret
              key: oracle-jdbc-url
        - name: database.user
          valueFrom:
            secretKeyRef:
              name: oracledb-service-broker-secret
              key: oracle-username
        - name: database.password
          valueFrom:
            secretKeyRef:
              name: oracledb-service-broker-secret
              key: oracle-password
        ports:
        - containerPort: 8080
