apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: supplier-helidon-se
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: supplier
        version: helidon-se
    spec:
      initContainers:
      - name: decode-creds
        command:
        - bash
        - -c
        - "for i in `ls -1 /tmp/creds | grep -v user_name`; do cat /tmp/creds/$i  | base64 --decode > /creds/$i; done; ls -l /creds/*;"
        image: oraclelinux:7.5
        volumeMounts:
        - name: creds-raw
          mountPath: /tmp/creds
          readOnly: false
        - name: creds
          mountPath: /creds
      containers:
      - name: supplier
        image: us-phoenix-1.ocir.io/stevengreenberginc/paul.parkinson/msdataworkshop/supplier-helidon-se:0.1
        imagePullPolicy: Always
        env:
        - name: database.user
          value: "inventoryuser"
        - name: database.password
          valueFrom:
            secretKeyRef:
              name: atp-user-cred-inventoryuser
              key: password
        - name: database.url
          value: "jdbc:oracle:thin:@inventorydb_high?TNS_ADMIN=/msdataworkshop/creds"
        - name: inventoryqueuename
          value: "inventoryqueue"
        - name: WALLET_PWD
          valueFrom:
            secretKeyRef:
              name: atp-user-cred-inventoryuser
              key: walletPassword
        volumeMounts:
        - name: creds
          mountPath: /msdataworkshop/creds
        ports:
        - containerPort: 8080
      restartPolicy: Always
      volumes:
      - name: creds-raw
        secret:
          secretName: atp-demo-binding-inventory
      - name: creds
        emptyDir: {}
