apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-helidon
spec:
  selector:
    matchLabels:
      app: order
#  namespaceSelector:
#    matchNames:
#    - msdataworkshop
  endpoints:
  - port: http
#    interval: 30s