apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-helidon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order
        version: helidon-mp
    spec:
      containers:
      - name: order
        image: docker.io/paulparkinson/order-helidon:0.1
        imagePullPolicy: Always
        env:
        - name: oracle.ucp.jdbc.PoolDataSource.atp1.URL
          valueFrom:
            secretKeyRef:
              name: oracledb-service-broker-secret
              key: oracle-jdbc-url
        - name: oracle.ucp.jdbc.PoolDataSource.atp1.user
          valueFrom:
            secretKeyRef:
              name: oracledb-service-broker-secret
              key: oracle-username
        - name: oracle.ucp.jdbc.PoolDataSource.atp1.password
          valueFrom:
            secretKeyRef:
              name: oracledb-service-broker-secret
              key: oracle-password
        ports:
        - containerPort: 8080
