apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inventoryadmin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inventoryadmin
        version: helidon
    spec:
      # The credential files in the secret are base64 encoded twice and hence they need to be decoded for the programs to use them.
      # This decode-creds initContainer takes care of decoding the files and writing them to a shared volume from which jdbc-app contianer
      # can read them and use it for connecting to ATP.
      initContainers:
      - name: decode-creds
        command:
        - bash
        - -c
        - "for i in `ls -1 /tmp/creds | grep -v user_name`; do cat /tmp/creds/$i  | base64 --decode > /creds/$i; done; ls -l /creds/*;"
        image: oraclelinux:7.5
        volumeMounts:
        - name: creds-raw
          mountPath: /tmp/creds
          readOnly: false
        - name: creds
          mountPath: /creds
      containers:
      - name: helidonatp
        image: us-phoenix-1.ocir.io/stevengreenberginc/paul.parkinson/msdataworkshop/helidonatp:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: oracle.ucp.jdbc.PoolDataSource.atp1.user
          value: "admin"
        - name: oracle.ucp.jdbc.PoolDataSource.atp1.password
          value: "WelcomeInventory123"
        - name: oracle.ucp.jdbc.PoolDataSource.atp1.URL
          value: "jdbc:oracle:thin:@inventorydb_high?TNS_ADMIN=/db-demo/creds"
#        - name: oracle.ucp.jdbc.PoolDataSource.atp1.URL
#          value: "jdbc:oracle:thin:@inventorydb_high"
#        - name: TNS_NAME
#          value: "inventorydb_high"
#        - name: TNS_ADMIN
#          value: "/db-demo/creds"
        # Pass  Wallet password to enable application to read Oracle wallet. The password is managed by the user and hence not part of the secret created by the binding request.
        # In this example we read the password form secret atp-user-cred-inventory that is required to be created by the user.
        - name: WALLET_PWD
          valueFrom:
            secretKeyRef:
              name: atp-user-cred-inventory
              key: walletPassword
        volumeMounts:
        - name: creds
          mountPath: /db-demo/creds
      volumes:
      # Volume for mouting the credentials file from Secret created by binding request.
      - name: creds-raw
        secret:
          secretName: atp-demo-binding-inventory
      # Shared Volume in which init-continer will save the decoded credential files and the jdbc-app container reads.
      - name: creds
        emptyDir: {}
